import { makeStyles } from '@mui/styles';
import { Theme } from '@mui/material/styles';

export const useFinishStyles = makeStyles<Theme>((theme) => ({
  container: {
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  iconCircle: {
    width: '60px',
    height: '60px',
    backgroundColor: '#22c55e',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto',
  },
  title: {
    fontWeight: 'bold !important',
    color: '#111827',
    fontSize: '22px !important',
    lineHeight: '28px',
  },
  subtitle: {
    color: '#64748b',
    fontSize: '13px',
    maxWidth: '672px',
    margin: '0 auto',
  },
  styledCard: {
    padding: '8px',
    background: 'linear-gradient(to right, #eff6ff, #e0e7ff)',
    border: '1px solid #bfdbfe',
  },
  cardTitle: {
    fontWeight: 600,
    color: '#111827',
    fontSize: '14px',
    marginBottom: '4px',
  },
  featureGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(1, 1fr)',
    gap: '4px',
    '@media (min-width: 900px)': {
      gridTemplateColumns: 'repeat(3, 1fr)',
    },
  },
  featureCard: {
    textAlign: 'center',
  },
  featureIcon: {
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 4px auto',
    '& .MuiSvgIcon-root': {
      width: '18px',
      height: '18px',
    },
  },
  featureTitle: {
    fontWeight: 500,
    color: '#111827',
    fontSize: '12px',
  },
  featureDesc: {
    color: '#64748b',
    fontSize: '11px',
  },
  stepsSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  stepsTitle: {
    fontWeight: 600,
    color: '#111827',
    fontSize: '13px',
  },
  stepsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  stepItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    textAlign: 'left',
    backgroundColor: '#f9fafb',
    padding: '6px',
    borderRadius: '8px',
    fontSize: '12px',
  },
  stepIcon: {
    width: '24px',
    height: '24px',
    backgroundColor: '#2563eb',
    color: 'white',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 600,
    fontSize: '12px',
  },
  stepTitle: {
    fontWeight: 500,
    color: '#111827',
    fontSize: '12px',
  },
  stepDesc: {
    color: '#64748b',
    fontSize: '11px',
  },
  buttonSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  finishButton: {
    width: '100%',
    backgroundColor: '#22c55e',
    color: 'white',
    padding: '10px 0',
    fontSize: '15px',
    fontWeight: 700,
    border: 'none',
    boxShadow: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '12px',
    textAlign: 'center',
    lineHeight: 1.2,
    '&:hover': {
      backgroundColor: '#16a34a',
    },
  },
  helperText: {
    fontSize: '10px',
    color: '#64748b',
  },
})); 